# Final Result

In [1]:
import pandas as pd

In [2]:
pd.read_csv(".//Model_Prediction//In-Sample-MSE.csv",index_col=0)

                               In-Sample-MSE
DecisionTree                        1.112309
GradientBoosting                   54.550886
RandomForestQuantileRegressor      78.050718
RandomForest                       74.329261
Bagging                            66.878244

In [3]:
pd.read_csv(".//Model_Prediction//In-Sample-Efficiency.csv",index_col=0)

                               In-Sample-Efficiency
DecisionTree                               0.952400
GradientBoosting                           0.859148
RandomForestQuantileRegressor              0.896589
RandomForest                               0.873159
Bagging                                    0.902692

In [7]:
pd.read_csv(".//Model_Prediction//Out-Sample-MSE.csv",index_col=0)

                               Out-Sample-MSE
DecisionTree                      1183.410397
GradientBoosting                   489.094265
RandomForestQuantileRegressor      296.629900
RandomForest                       318.541924
Bagging                            314.264443

In [4]:
final_result = pd.read_csv(".//Model_Prediction//Bagging.csv")

In [5]:
final_result

,Unnamed: 0,productID,brandID,attribute1,attribute2,attribute3,attribute4,clickVolume,avgOriginalUnitPrice,avgFinalUnitPrice,...,meanAge,gender,meanEducation,maritalStatus,plus,meanPurchasePower,meanUserLevel,meanCityLevel,sales,inventory
0,0,0,4,3.0,90.0,2,15.410308,644.0,129.0,127.428571,...,36.000000,0.142857,3.333333,0.666667,0.285714,2.000000,2.571429,2.833333,12.0,13.0
1,1,88,36,4.0,100.0,1,4.415871,198.0,249.9,135.666667,...,40.666667,0.333333,2.500000,0.333333,0.000000,2.000000,2.000000,3.333333,3.0,4.0
2,2,82,11,3.0,100.0,2,9.012597,552.0,99.0,49.000000,...,20.000000,0.000000,3.000000,0.000000,0.000000,2.000000,2.000000,3.000000,19.0,20.0
3,3,38,14,3.0,80.0,3,17.763691,1319.0,79.0,68.454545,...,28.666667,0.600000,2.571429,0.533333,0.142857,2.666667,2.047619,3.000000,30.0,31.0
4,4,21,26,2.0,50.0,5,2.248642,851.0,69.9,55.733333,...,32.105263,0.421053,2.894737,0.421053,0.095238,2.210526,2.761905,1.947368,29.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1538,1538,43,12,3.0,60.0,1,8.618363,277.0,139.0,66.657143,...,33.333333,0.333333,3.000000,0.600000,0.285714,2.000000,3.000000,2.166667,6.0,7.0
1539,1539,36,19,3.0,60.0,5,2.729973,694.0,119.0,60.321951,...,30.387097,0.225806,3.071429,0.607143,0.303030,2.214286,2.666667,2.032258,27.0,27.0
1540,1540,24,26,2.0,50.0,2,2.342957,941.0,94.9,94.900000,...,32.500000,0.500000,2.750000,0.500000,0.250000,2.000000,2.250000,2.250000,19.0,19.0
1541,1541,36,19,3.0,60.0,2,23.102118,188.0,119.0,71.900000,...,27.500000,0.125000,3.125000,0.625000,0.000000,2.375000,1.666667,2.714286,6.0,7.0
1542,1542,90,35,4.0,100.0,1,13.045102,237.0,230.0,163.571429,...,30.000000,0.200000,3.400000,0.200000,0.500000,2.000000,3.000000,1.800000,5.0,6.0

In [6]:
final_result.to_csv("group4.csv")